name: 🐛 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much information as you can. It helps us better understand the problem and fix it faster.
  - type: textarea
    id: version
    attributes:
      label: What is your Bitcoin Beach Wallet version?
      description: You can see the version in the footer's of settings page
      placeholder: I'm running Bitcoin Beach Wallet v1.X.X.X
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: browser
    attributes:
      label: What browser do you use?
      description: Provide your browser and it's version. If you replicated issues on multiple browsers, let us know which ones.
      placeholder: For example Safari 15.00, Chrome 10.0, Tor, Edge, etc
    validations:
      required: false
  - type: textarea
    id: additonal
    attributes:
      label: Additional information
      description: Feel free to provide additional information. Screenshots are always helpful.
  - type: checkboxes
    id: terms
    attributes:
      label: Are you sure this is a bug report?
      description: By submitting this report, you agree that this is not a support or a feature request. For general questions please read our [documentation](https://dev.galoy.io/docs/). You can ask questions in  [on our community chat](https://chat.galoy.io/)
      options:
        - label: I confirm this is a bug report
          required: true

